// packages/ube/vue/FormInputText.vue
<template>
  <div
    ref="wrapper"
    :style="{ width, height }"
    :class="['form-input', inputClasses]"
  >
    <!-- Search mode wrapper -->
    <template v-if="search">
      <form
        role="search"
        :aria-label="label"
        @submit.prevent="handleSubmit"
      >
        <input
          ref="input"
          :id="id"
          :type="type"
          :value="value"
          :placeholder="placeholder"
          :disabled="disabled"
          :class="`form-input__field${inputClassName ? ` ${inputClassName}` : ''}`"
          @input="$emit('update:value', $event.target.value)"
        />
        <button
          v-if="clearable && value"
          type="button"
          :aria-label="clearAriaLabel"
          :class="`form-input__clear${clearButtonClassName ? ` ${clearButtonClassName}` : ''}`"
          @click="handleClear"
        >
          {{ clearIcon }}
        </button>
        <button
          v-if="showSubmit && !liveSearch"
          type="submit"
          :disabled="disabled"
          :aria-label="submitAriaLabel"
          class="form-input__submit"
        >
          🔍
        </button>
      </form>
    </template>

    <!-- Clear mode wrapper -->
    <template v-else-if="clearable">
      <input
        ref="input"
        :id="id"
        :type="type"
        :value="value"
        :placeholder="placeholder"
        :disabled="disabled"
        :class="`form-input__field${inputClassName ? ` ${inputClassName}` : ''}`"
        @input="$emit('update:value', $event.target.value)"
      />
      <button
        v-if="value"
        type="button"
        :aria-label="clearAriaLabel"
        :class="`form-input__clear${clearButtonClassName ? ` ${clearButtonClassName}` : ''}`"
        @click="handleClear"
      >
        {{ clearIcon }}
      </button>
    </template>

    <!-- Plain mode -->
    <template v-else>
      <input
        ref="input"
        :id="id"
        :type="type"
        :value="value"
        :placeholder="placeholder"
        :disabled="disabled"
        :class="`form-input__field${inputClassName ? ` ${inputClassName}` : ''}`"
        @input="$emit('update:value', $event.target.value)"
      />
    </template>
  </div>
</template>

<script>
import { ref, computed, watch } from 'vue'
import '../../form-input-text.css'

export default {
  name: 'FormInputText',
  props: {
    id: String,
    type: { type: String, default: 'text' },
    value: String,
    search: { type: Boolean, default: false },
    liveSearch: { type: Boolean, default: false },
    showSubmit: { type: Boolean, default: true },
    clearable: { type: Boolean, default: false },
    placeholder: String,
    disabled: { type: Boolean, default: false },
    label: String,
    width: { type: String, default: '100%' },
    height: String,
    submitAriaLabel: { type: String, default: 'Search' },
    clearAriaLabel: { type: String, default: 'Clear' },
    clearIcon: { type: String, default: '✕' },
    wrapClassName: { type: String, default: '' },
    inputClassName: { type: String, default: '' },
    clearButtonClassName: { type: String, default: '' },
  },
  emits: ['update:value', 'submit', 'clear'],
  setup(props, { emit }) {
    const input = ref(null)
    const wrapper = ref(null)

    const inputClasses = computed(() => {
      const classes = ['form-input']
      if (props.search) {
        classes.push('form-input--search')
        if (props.liveSearch) classes.push('form-input--live')
      } else if (props.clearable) {
        classes.push('form-input--with-clear')
      }
      if (props.wrapClassName) classes.push(props.wrapClassName)
      return classes.join(' ')
    })

    const handleSubmit = () => {
      emit('submit', props.value)
    }

    const handleClear = () => {
      emit('clear')
      emit('update:value', '')
      input.value?.focus()
    }

    return {
      input,
      wrapper,
      inputClasses,
      handleSubmit,
      handleClear,
    }
  },
}
</script>

// packages/ube/FormInputText.jsx
import { useRef } from 'react'
import './form-control-button.css'
import './form-input.css'

/**
 * Consolidated text input wrapper supporting search and clear modes.
 *
 * search={true}      : renders form[role="search"], shows submit button (unless liveSearch=true)
 * liveSearch={true}  : fires onChange on keystroke, hides submit button
 * clearable={true}   : shows clear button when input has value
 * clearIcon          : custom clear button content (default: ✕)
 *
 * Pair with a visible <label> or pass label to set aria-label on wrapper.
 */
export default function FormInputText({
  id,
  type = 'text',
  value,
  onChange,
  onSubmit,
  onClear,
  search = false,
  liveSearch = false,
  clearable = false,
  placeholder,
  disabled = false,
  label,
  submitAriaLabel = 'Search',
  clearAriaLabel = 'Clear',
  clearIcon = '✕',
  wrapClassName = '',
  inputClassName = '',
  clearButtonClassName = '',
  inputRef: externalRef,
  ...rest
}) {
  const internalRef = useRef(null)
  const ref = externalRef || internalRef

  const handleSubmit = (e) => {
    e.preventDefault()
    onSubmit?.(value)
  }

  const handleClear = () => {
    if (onClear) {
      onClear()
    } else {
      onChange('')
    }
    ref.current?.focus()
  }

  const inputElement = (
    <input
      ref={ref}
      id={id}
      type={type}
      value={value}
      onChange={e => onChange(e.target.value)}
      disabled={disabled}
      placeholder={placeholder}
      className={`form-input__field${inputClassName ? ` ${inputClassName}` : ''}`}
      {...rest}
    />
  )

  const clearButton = value && (
    <button
      type="button"
      onClick={handleClear}
      aria-label={clearAriaLabel}
      className={`form-input__clear${clearButtonClassName ? ` ${clearButtonClassName}` : ''}`}
    >
      {clearIcon}
    </button>
  )

  // Search mode: form[role="search"] with optional submit button
  if (search) {
    return (
      <form
        role="search"
        className={`form-input form-input--search${liveSearch ? ' form-input--live' : ''}${wrapClassName ? ` ${wrapClassName}` : ''}`}
        onSubmit={handleSubmit}
        aria-label={label}
      >
        {inputElement}
        {clearable && clearButton}
        {!liveSearch && (
          <button
            type="submit"
            disabled={disabled}
            aria-label={submitAriaLabel}
            className="form-input__submit"
          >
            🔍
          </button>
        )}
      </form>
    )
  }

  // Clear mode: div wrapper with clear button
  if (clearable) {
    return (
      <div className={`form-input form-input--with-clear${wrapClassName ? ` ${wrapClassName}` : ''}`}>
        {inputElement}
        {clearButton}
      </div>
    )
  }

  // Plain mode: just the input
  return inputElement
}
