// packages/ube/vue/ButtonBack.vue
<template>
  <ube-button-back
    ref="el"
    :disabled="disabled"
    :label="label"
    :title="title"
    @click="$emit('click', $event)"
  />
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'ButtonBack',
  props: {
    disabled: Boolean,
    label: String,
    title: String,
  },
  emits: ['click'],
  methods: {
    focus() {
      this.$refs.el?.focus()
    },
  },
}
</script>

// packages/ube/angular/button-back.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'
import '@ulam/ube/core'

@Component({
  selector: 'ube-button-back',
  template: `<ube-button-back
    #el
    [attr.disabled]="disabled"
    [attr.label]="label"
    [attr.title]="title"
    (click)="click.emit($event)"
  ></ube-button-back>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ButtonBackComponent {
  @ViewChild('el') el!: ElementRef<any>
  @Input() disabled = false
  @Input() label?: string
  @Input() title?: string
  @Output() click = new EventEmitter<any>()

  focus() {
    this.el?.nativeElement?.focus()
  }
}
