// packages/ube/vue/FormControlRadio.vue
<template>
  <ube-form-control-radio
    ref="el"
    :name="name"
    :value="value"
    :label="label"
    :checked="checked"
    :disabled="disabled"
    @change="$emit('update:checked', $event.target.checked)"
  />
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'FormControlRadio',
  props: {
    name: String,
    value: String,
    label: String,
    checked: Boolean,
    disabled: Boolean,
  },
  emits: ['update:checked'],
}
</script>

// packages/ube/angular/form-control-radio.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'
import '@ulam/ube/core'

@Component({
  selector: 'ube-form-control-radio',
  template: `<ube-form-control-radio
    #el
    [attr.name]="name"
    [attr.value]="value"
    [attr.label]="label"
    [attr.checked]="checked"
    [attr.disabled]="disabled"
    (change)="checkedChange.emit($event.target.checked)"
  ></ube-form-control-radio>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class FormControlRadioComponent {
  @ViewChild('el') el!: ElementRef<any>
  @Input() name?: string
  @Input() value?: string
  @Input() label?: string
  @Input() checked = false
  @Input() disabled = false
  @Output() checkedChange = new EventEmitter<boolean>()
}
