// packages/ube/vue/FormControlRadioGroup.vue
<template>
  <fieldset
    ref="wrapper"
    :aria-disabled="disabled ? 'true' : undefined"
    class="radio-group-wrapper"
  >
    <legend class="sr-only">{{ legend }}</legend>
    <div class="radio-group">
      <label v-for="opt in options" :key="opt.value" class="radio-control">
        <input
          type="radio"
          :name="name"
          :value="opt.value"
          :checked="value === opt.value"
          :disabled="disabled"
          @change="handleChange(opt.value)"
        />
        <span>{{ opt.label }}</span>
      </label>
    </div>
  </fieldset>
</template>

<script>
export default {
  name: 'FormControlRadioGroup',
  props: {
    legend: { type: String, required: true },
    name: { type: String, required: true },
    value: { type: [String, Number], default: null },
    options: {
      type: Array,
      required: true,
      validator: (v) => v.every((opt) => typeof opt.value !== 'undefined' && typeof opt.label === 'string'),
    },
    disabled: { type: Boolean, default: false },
  },
  emits: ['update:value'],
  methods: {
    handleChange(newValue) {
      if (!this.disabled) {
        this.$emit('update:value', newValue)
      }
    },
  },
}
</script>

<style scoped>
.radio-group-wrapper {
  border: none;
  padding: 0;
  margin: 0;
}

.radio-group {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}

.radio-control {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  cursor: pointer;
}

.radio-control input[type='radio'] {
  cursor: pointer;
}

.radio-control input[type='radio']:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}
</style>

// packages/ube/angular/form-control-radio-group.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef } from '@angular/core'

interface RadioOption {
  value: string | number
  label: string
}

/**
 * RadioGroup: fieldset + legend + FormControlRadio options.
 * Angular component for grouping regular radio buttons with aria-disabled support.
 */
@Component({
  selector: 'ube-form-control-radio-group',
  template: `
    <fieldset
      #wrapper
      [attr.aria-disabled]="disabled ? 'true' : undefined"
    >
      <legend class="sr-only">{{ legend }}</legend>
      <div class="radio-group">
        <label *ngFor="let opt of options" class="radio-control">
          <input
            type="radio"
            [name]="name"
            [value]="opt.value"
            [checked]="value === opt.value"
            [disabled]="disabled"
            (change)="handleChange(opt.value)"
          />
          <span>{{ opt.label }}</span>
        </label>
      </div>
    </fieldset>
  `,
  styleUrls: ['../../form-control-radio.css'],
})
export class FormControlRadioGroupComponent {
  @ViewChild('wrapper') wrapper!: ElementRef<HTMLFieldSetElement>

  @Input() legend: string = ''
  @Input() name: string = ''
  @Input() value: string | number | null = null
  @Input() options: RadioOption[] = []
  @Input() disabled = false

  @Output() valueChange = new EventEmitter<string | number>()

  handleChange(newValue: string | number) {
    if (!this.disabled) {
      this.valueChange.emit(newValue)
    }
  }
}
