// packages/ube/ng/badge.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'
import '@ulam/ube/core'

@Component({
  selector: 'ube-badge',
  template: `<ube-badge
    #el
    [attr.variant]="variant"
    [attr.is-button]="isButton"
    (click)="click.emit($event)"
  ><ng-content></ng-content></ube-badge>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class BadgeComponent {
  @ViewChild('el') el!: ElementRef<any>
  @Input() variant?: string
  @Input() isButton = false
  @Input() set bgColor(val: string | undefined) {
    if (this.el && val) {
      this.el.nativeElement.style.setProperty('--badge-bg', val)
    }
  }
  @Input() set textColor(val: string | undefined) {
    if (this.el && val) {
      this.el.nativeElement.style.setProperty('--badge-color', val)
    }
  }
  @Output() click = new EventEmitter<any>()
}

// packages/ube/vue/Badge.vue
<template>
  <ube-badge
    ref="el"
    :variant="variant"
    :is-button="isButton"
    @click="$emit('click', $event)"
  >
    <slot />
  </ube-badge>
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'Badge',
  props: {
    variant: String,
    isButton: Boolean,
    bgColor: String,
    textColor: String,
  },
  emits: ['click'],
  watch: {
    bgColor(val) {
      this.$refs.el?.style.setProperty('--badge-bg', val)
    },
    textColor(val) {
      this.$refs.el?.style.setProperty('--badge-color', val)
    },
  },
  mounted() {
    if (this.bgColor) {
      this.$refs.el.style.setProperty('--badge-bg', this.bgColor)
    }
    if (this.textColor) {
      this.$refs.el.style.setProperty('--badge-color', this.textColor)
    }
  },
}
</script>
