// packages/ube/angular/button.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, forwardRef } from '@angular/core'
import { NG_VALUE_ACCESSOR } from '@angular/forms'

/**
 * Unified button component supporting text, icon, or icon+text layouts.
 * Angular standalone component wrapping core Button logic.
 */
@Component({
  selector: 'ube-button',
  template: `
    <button
      #btn
      type="button"
      [class]="buttonClasses"
      [disabled]="disabled || busy"
      [attr.aria-label]="label"
      [attr.aria-busy]="busy ? true : undefined"
      [attr.title]="title"
      (click)="handleClick($event)"
    >
      <span *ngIf="iconPosition === 'start' && displayIcon" class="btn-icon">
        <ng-container *ngComponentOutlet="displayIcon"></ng-container>
      </span>
      <ng-content></ng-content>
      <span *ngIf="iconPosition === 'end' && displayIcon" class="btn-icon">
        <ng-container *ngComponentOutlet="displayIcon"></ng-container>
      </span>
    </button>
  `,
  styleUrls: ['../../buttons.css'],
  standalone: true,
})
export class ButtonComponent {
  @ViewChild('btn') btn!: ElementRef<HTMLButtonElement>

  @Input() label?: string
  @Input() activeLabel?: string
  @Input() icon?: any
  @Input() activeIcon?: any
  @Input() active = false
  @Input() variant: 'primary' | 'secondary' | 'tertiary' | 'accent' = 'primary'
  @Input() disabled = false
  @Input() busy = false
  @Input() fullWidth = false
  @Input() error = false
  @Input() align: 'left' | 'center' | 'right' = 'center'
  @Input() size: 'compact' | 'default' | 'large' = 'default'
  @Input() iconPosition: 'start' | 'end' = 'start'
  @Input() title?: string

  @Output() click = new EventEmitter<MouseEvent>()

  get displayIcon() {
    return this.active ? this.activeIcon : this.icon
  }

  get displayLabel() {
    return this.active ? this.activeLabel : this.label
  }

  get isIconOnly() {
    return this.displayIcon && !this.hasText()
  }

  get buttonClasses(): string {
    const classes: string[] = []

    if (this.isIconOnly) {
      classes.push('btn--icon')
      if (this.variant === 'accent') classes.push('btn--icon-accent')
      else if (this.variant === 'tertiary') classes.push('btn--icon-tertiary')
    } else {
      classes.push('btn')
      classes.push(`btn--${this.variant}`)
    }

    if (this.active) classes.push('btn__field--success')
    if (this.busy) classes.push('btn--busy')
    if (this.fullWidth) classes.push('btn--full-width')
    if (!this.isIconOnly && this.align !== 'center') classes.push(`btn--align-${this.align}`)
    if (!this.isIconOnly && this.size !== 'default') classes.push(`btn--size-${this.size}`)
    if (this.error) classes.push('btn--error')

    return classes.join(' ')
  }

  private hasText(): boolean {
    // Check if ng-content has text content
    // For simplicity, return true if not icon-only (will be determined by usage)
    return true
  }

  handleClick(event: MouseEvent) {
    if (!this.disabled && !this.busy) {
      this.click.emit(event)
    }
  }

  focus() {
    this.btn?.nativeElement?.focus()
  }
}

// packages/ube/vue/Button.vue
<template>
  <button
    ref="btn"
    type="button"
    :class="buttonClasses"
    :disabled="disabled || busy"
    :aria-label="label"
    :aria-busy="busy ? true : undefined"
    :title="title"
    @click="handleClick"
  >
    <span v-if="iconPosition === 'start' && displayIcon" class="btn-icon">
      <component :is="displayIcon" />
    </span>
    <slot></slot>
    <span v-if="iconPosition === 'end' && displayIcon" class="btn-icon">
      <component :is="displayIcon" />
    </span>
  </button>
</template>

<script>
import '../../buttons.css'

export default {
  name: 'Button',
  props: {
    label: String,
    activeLabel: String,
    icon: Object,
    activeIcon: Object,
    active: { type: Boolean, default: false },
    variant: { type: String, default: 'primary', validator: (v) => ['primary', 'secondary', 'tertiary', 'accent'].includes(v) },
    disabled: { type: Boolean, default: false },
    busy: { type: Boolean, default: false },
    fullWidth: { type: Boolean, default: false },
    error: { type: Boolean, default: false },
    align: { type: String, default: 'center', validator: (v) => ['left', 'center', 'right'].includes(v) },
    size: { type: String, default: 'default', validator: (v) => ['compact', 'default', 'large'].includes(v) },
    iconPosition: { type: String, default: 'start', validator: (v) => ['start', 'end'].includes(v) },
    title: String,
  },
  emits: ['click'],
  computed: {
    displayIcon() {
      return this.active ? this.activeIcon : this.icon
    },
    displayLabel() {
      return this.active ? this.activeLabel : this.label
    },
    isIconOnly() {
      return this.displayIcon && !this.$slots.default
    },
    buttonClasses() {
      const classes = []

      if (this.isIconOnly) {
        classes.push('btn--icon')
        if (this.variant === 'accent') classes.push('btn--icon-accent')
        else if (this.variant === 'tertiary') classes.push('btn--icon-tertiary')
      } else {
        classes.push('btn')
        classes.push(`btn--${this.variant}`)
      }

      if (this.active) classes.push('btn__field--success')
      if (this.busy) classes.push('btn--busy')
      if (this.fullWidth) classes.push('btn--full-width')
      if (!this.isIconOnly && this.align !== 'center') classes.push(`btn--align-${this.align}`)
      if (!this.isIconOnly && this.size !== 'default') classes.push(`btn--size-${this.size}`)
      if (this.error) classes.push('btn--error')

      return classes.join(' ')
    },
  },
  methods: {
    handleClick(event) {
      if (!this.disabled && !this.busy) {
        this.$emit('click', event)
      }
    },
    focus() {
      this.$refs.btn?.focus()
    },
  },
}
</script>
