// packages/ube/ButtonText.jsx
import { forwardRef } from 'react'
import './button-text.css'

const Button = forwardRef(function Button({
  children,
  label,
  activeLabel,
  icon,
  activeIcon,
  active,
  variant = 'primary',
  disabled,
  fullWidth,
  error,
  title,
  onClick,
  className = '',
  ...rest
}, ref) {
  const variantClass = `btn--${variant}`
  const baseClasses = `btn ${variantClass}`
  const stateClass = active ? ' btn__field--success' : ''
  const disabledClass = disabled ? ' btn--disabled' : ''
  const fullWidthClass = fullWidth ? ' btn--full-width' : ''
  const errorClass = error ? ' btn--error' : ''

  const displayIcon = active ? activeIcon : icon
  const displayLabel = active ? activeLabel : label

  const finalClassName = `${baseClasses}${stateClass}${disabledClass}${fullWidthClass}${errorClass}${className ? ` ${className}` : ''}`

  return (
    <button
      ref={ref}
      type="button"
      onClick={disabled ? undefined : onClick}
      aria-disabled={disabled || undefined}
      aria-label={displayLabel}
      title={title}
      className={finalClassName}
      {...rest}
    >
      {displayIcon && (
        <span className="btn-icon">
          {displayIcon}
        </span>
      )}
      {children}
    </button>
  )
})

export default Button

// packages/ube/vue/ButtonText.vue
<template>
  <ube-button-text
    ref="el"
    :variant="variant"
    :disabled="disabled"
    :active="active"
    :full-width="fullWidth"
    :label="label"
    :active-label="activeLabel"
    :title="title"
    @click="$emit('click', $event)"
  />
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'ButtonText',
  props: {
    variant: String,
    disabled: Boolean,
    active: Boolean,
    fullWidth: Boolean,
    label: String,
    activeLabel: String,
    title: String,
    icon: Object,
    activeIcon: Object,
  },
  emits: ['click'],
  methods: {
    focus() {
      this.$refs.el?.focus()
    },
  },
  watch: {
    icon(val) {
      this.$refs.el.icon = val
    },
    activeIcon(val) {
      this.$refs.el.activeIcon = val
    },
  },
  mounted() {
    if (this.icon) {
      this.$refs.el.icon = this.icon
    }
    if (this.activeIcon) {
      this.$refs.el.activeIcon = this.activeIcon
    }
  },
}
</script>
