// packages/ube/ng/form-control-radio-chip.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'
import '@ulam/ube/core'

@Component({
  selector: 'ube-form-control-radio-chip',
  template: `<ube-form-control-radio-chip
    #el
    [attr.name]="name"
    [attr.value]="value"
    [attr.label]="label"
    [attr.current]="current"
    (change)="change.emit($event.detail.value)"
  ></ube-form-control-radio-chip>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class FormControlRadioChipComponent {
  @ViewChild('el') el!: ElementRef<any>
  @Input() name?: string
  @Input() value?: string
  @Input() label?: string
  @Input() current?: string
  @Output() change = new EventEmitter<string>()
}

// packages/ube/vue/FormControlRadioChip.vue
<template>
  <ube-form-control-radio-chip
    ref="el"
    :name="name"
    :value="value"
    :label="label"
    :current="current"
    @change="$emit('change', $event.detail.value)"
  />
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'FormControlRadioChip',
  props: {
    name: String,
    value: String,
    label: String,
    current: String,
  },
  emits: ['change'],
}
</script>
