// packages/ube/FormControlRadioChip.jsx
import './form-control-radio-chip.css'

export default function FormControlRadioChip({ name, value, label, current, onChange }) {
  const isActive = current === value
  return (
    <label className={`radio-chip${isActive ? ' radio-chip--active' : ''}`}>
      <input
        type="radio"
        name={name}
        value={value}
        checked={isActive}
        onChange={() => onChange(value)}
        className="radio-chip__input"
        aria-label={label.replace(/\n/g, ' ')}
      />
      <span className="radio-chip__indicator" aria-hidden="true" />
      <span aria-hidden="true">
        {label.split('\n').flatMap((part, i) => i === 0 ? [part] : [<br key={i} />, part])}
      </span>
    </label>
  )
}

// packages/ube/vue/FormControlRadioChip.vue
<template>
  <ube-form-control-radio-chip
    ref="el"
    :name="name"
    :value="value"
    :label="label"
    :current="current"
    @change="$emit('change', $event.detail.value)"
  />
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'FormControlRadioChip',
  props: {
    name: String,
    value: String,
    label: String,
    current: String,
  },
  emits: ['change'],
}
</script>
