// packages/ube/ng/form-input-with-clear.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'
import '@ulam/ube/core'

@Component({
  selector: 'ube-form-input-with-clear',
  template: `<ube-form-input-with-clear
    #el
    [attr.value]="value"
    [attr.placeholder]="placeholder"
    [attr.disabled]="disabled"
    (change)="valueChange.emit($event.target.value)"
    (clear)="clear.emit()"
  ></ube-form-input-with-clear>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class FormInputWithClearComponent {
  @ViewChild('el') el!: ElementRef<any>
  @Input() value?: string
  @Input() placeholder?: string
  @Input() disabled = false
  @Output() valueChange = new EventEmitter<string>()
  @Output() clear = new EventEmitter<void>()
}

// packages/ube/vue/FormInputWithClear.vue
<template>
  <ube-form-input-with-clear
    ref="el"
    :value="value"
    :placeholder="placeholder"
    :disabled="disabled"
    @change="$emit('update:value', $event.target.value)"
    @clear="$emit('clear')"
  />
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'FormInputWithClear',
  props: {
    value: String,
    placeholder: String,
    disabled: Boolean,
  },
  emits: ['update:value', 'clear'],
}
</script>
