// packages/ube/angular/form-input-text.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef } from '@angular/core'

@Component({
  selector: 'ube-form-input-text',
  template: `
    <div
      #wrapper
      [style.width]="width"
      [style.height]="height"
      [ngClass]="['form-input', inputClasses]"
    >
      <!-- Search mode -->
      <ng-container *ngIf="search">
        <form
          role="search"
          [attr.aria-label]="label"
          (ngSubmit)="handleSubmit()"
        >
          <input
            #input
            [attr.id]="id"
            [attr.type]="type"
            [value]="value"
            [attr.placeholder]="placeholder"
            [disabled]="disabled"
            [ngClass]="['form-input__field', inputClassName]"
            (input)="valueChange.emit($event.target.value)"
          />
          <button
            *ngIf="clearable && value"
            type="button"
            [attr.aria-label]="clearAriaLabel"
            [ngClass]="['form-input__clear', clearButtonClassName]"
            (click)="handleClear()"
          >
            {{ clearIcon }}
          </button>
          <button
            *ngIf="showSubmit && !liveSearch"
            type="submit"
            [disabled]="disabled"
            [attr.aria-label]="submitAriaLabel"
            class="form-input__submit"
          >
            🔍
          </button>
        </form>
      </ng-container>

      <!-- Clear mode -->
      <ng-container *ngIf="!search && clearable">
        <input
          #input
          [attr.id]="id"
          [attr.type]="type"
          [value]="value"
          [attr.placeholder]="placeholder"
          [disabled]="disabled"
          [ngClass]="['form-input__field', inputClassName]"
          (input)="valueChange.emit($event.target.value)"
        />
        <button
          *ngIf="value"
          type="button"
          [attr.aria-label]="clearAriaLabel"
          [ngClass]="['form-input__clear', clearButtonClassName]"
          (click)="handleClear()"
        >
          {{ clearIcon }}
        </button>
      </ng-container>

      <!-- Plain mode -->
      <ng-container *ngIf="!search && !clearable">
        <input
          #input
          [attr.id]="id"
          [attr.type]="type"
          [value]="value"
          [attr.placeholder]="placeholder"
          [disabled]="disabled"
          [ngClass]="['form-input__field', inputClassName]"
          (input)="valueChange.emit($event.target.value)"
        />
      </ng-container>
    </div>
  `,
  styleUrls: ['../../form-input-text.css'],
})
export class FormInputTextComponent {
  @ViewChild('input') input!: ElementRef<HTMLInputElement>
  @ViewChild('wrapper') wrapper!: ElementRef<HTMLDivElement>

  @Input() id?: string
  @Input() type = 'text'
  @Input() value = ''
  @Input() search = false
  @Input() liveSearch = false
  @Input() showSubmit = true
  @Input() clearable = false
  @Input() placeholder?: string
  @Input() disabled = false
  @Input() label?: string
  @Input() width = '100%'
  @Input() height?: string
  @Input() submitAriaLabel = 'Search'
  @Input() clearAriaLabel = 'Clear'
  @Input() clearIcon = '✕'
  @Input() wrapClassName = ''
  @Input() inputClassName = ''
  @Input() clearButtonClassName = ''

  @Output() valueChange = new EventEmitter<string>()
  @Output() submit = new EventEmitter<string>()
  @Output() clear = new EventEmitter<void>()

  get inputClasses(): string {
    const classes: string[] = ['form-input']
    if (this.search) {
      classes.push('form-input--search')
      if (this.liveSearch) classes.push('form-input--live')
    } else if (this.clearable) {
      classes.push('form-input--with-clear')
    }
    if (this.wrapClassName) classes.push(this.wrapClassName)
    return classes.join(' ')
  }

  handleSubmit(): void {
    this.submit.emit(this.value)
  }

  handleClear(): void {
    this.clear.emit()
    this.valueChange.emit('')
    this.input?.nativeElement?.focus()
  }
}

// packages/ube/vue/FormInputText.vue
<template>
  <div
    ref="wrapper"
    :style="{ width, height }"
    :class="['form-input', inputClasses]"
  >
    <!-- Search mode wrapper -->
    <template v-if="search">
      <form
        role="search"
        :aria-label="label"
        @submit.prevent="handleSubmit"
      >
        <input
          ref="input"
          :id="id"
          :type="type"
          :value="value"
          :placeholder="placeholder"
          :disabled="disabled"
          :class="`form-input__field${inputClassName ? ` ${inputClassName}` : ''}`"
          @input="$emit('update:value', $event.target.value)"
        />
        <button
          v-if="clearable && value"
          type="button"
          :aria-label="clearAriaLabel"
          :class="`form-input__clear${clearButtonClassName ? ` ${clearButtonClassName}` : ''}`"
          @click="handleClear"
        >
          {{ clearIcon }}
        </button>
        <button
          v-if="showSubmit && !liveSearch"
          type="submit"
          :disabled="disabled"
          :aria-label="submitAriaLabel"
          class="form-input__submit"
        >
          🔍
        </button>
      </form>
    </template>

    <!-- Clear mode wrapper -->
    <template v-else-if="clearable">
      <input
        ref="input"
        :id="id"
        :type="type"
        :value="value"
        :placeholder="placeholder"
        :disabled="disabled"
        :class="`form-input__field${inputClassName ? ` ${inputClassName}` : ''}`"
        @input="$emit('update:value', $event.target.value)"
      />
      <button
        v-if="value"
        type="button"
        :aria-label="clearAriaLabel"
        :class="`form-input__clear${clearButtonClassName ? ` ${clearButtonClassName}` : ''}`"
        @click="handleClear"
      >
        {{ clearIcon }}
      </button>
    </template>

    <!-- Plain mode -->
    <template v-else>
      <input
        ref="input"
        :id="id"
        :type="type"
        :value="value"
        :placeholder="placeholder"
        :disabled="disabled"
        :class="`form-input__field${inputClassName ? ` ${inputClassName}` : ''}`"
        @input="$emit('update:value', $event.target.value)"
      />
    </template>
  </div>
</template>

<script>
import { ref, computed, watch } from 'vue'
import '../../form-input-text.css'

export default {
  name: 'FormInputText',
  props: {
    id: String,
    type: { type: String, default: 'text' },
    value: String,
    search: { type: Boolean, default: false },
    liveSearch: { type: Boolean, default: false },
    showSubmit: { type: Boolean, default: true },
    clearable: { type: Boolean, default: false },
    placeholder: String,
    disabled: { type: Boolean, default: false },
    label: String,
    width: { type: String, default: '100%' },
    height: String,
    submitAriaLabel: { type: String, default: 'Search' },
    clearAriaLabel: { type: String, default: 'Clear' },
    clearIcon: { type: String, default: '✕' },
    wrapClassName: { type: String, default: '' },
    inputClassName: { type: String, default: '' },
    clearButtonClassName: { type: String, default: '' },
  },
  emits: ['update:value', 'submit', 'clear'],
  setup(props, { emit }) {
    const input = ref(null)
    const wrapper = ref(null)

    const inputClasses = computed(() => {
      const classes = ['form-input']
      if (props.search) {
        classes.push('form-input--search')
        if (props.liveSearch) classes.push('form-input--live')
      } else if (props.clearable) {
        classes.push('form-input--with-clear')
      }
      if (props.wrapClassName) classes.push(props.wrapClassName)
      return classes.join(' ')
    })

    const handleSubmit = () => {
      emit('submit', props.value)
    }

    const handleClear = () => {
      emit('clear')
      emit('update:value', '')
      input.value?.focus()
    }

    return {
      input,
      wrapper,
      inputClasses,
      handleSubmit,
      handleClear,
    }
  },
}
</script>
