// packages/ube/FormControlRadio.jsx
import { forwardRef } from 'react'
import './form-controls.css'
import './form-control-radio.css'

const FormControlRadio = forwardRef(function FormControlRadio({
  name,
  value,
  checked,
  onChange,
  label,
  disabled,
  className = '',
  ...rest
}, ref) {
  return (
    <label className={`control__label${className ? ` ${className}` : ''}`}>
      <input
        ref={ref}
        type="radio"
        name={name}
        value={value}
        checked={checked}
        onChange={onChange}
        disabled={disabled}
        className="control"
        {...rest}
      />
      {label}
    </label>
  )
})

export default FormControlRadio

// packages/ube/vue/FormControlRadio.vue
<template>
  <ube-form-control-radio
    ref="el"
    :name="name"
    :value="value"
    :label="label"
    :checked="checked"
    :disabled="disabled"
    @change="$emit('update:checked', $event.target.checked)"
  />
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'FormControlRadio',
  props: {
    name: String,
    value: String,
    label: String,
    checked: Boolean,
    disabled: Boolean,
  },
  emits: ['update:checked'],
}
</script>
