// packages/ube/FormControlCheckbox.jsx
import { forwardRef } from 'react'
import './form-controls.css'
import './form-control-checkbox.css'

const FormControlCheckbox = forwardRef(function FormControlCheckbox({
  checked,
  onChange,
  label,
  disabled,
  className = '',
  ...rest
}, ref) {
  return (
    <label className={`control__label${className ? ` ${className}` : ''}`}>
      <input
        ref={ref}
        type="checkbox"
        checked={checked}
        onChange={onChange}
        disabled={disabled}
        className="control"
        {...rest}
      />
      {label}
    </label>
  )
})

export default FormControlCheckbox

// packages/ube/vue/FormControlCheckbox.vue
<template>
  <ube-form-control-checkbox
    ref="el"
    :value="value"
    :label="label"
    :checked="checked"
    :disabled="disabled"
    @change="$emit('update:checked', $event.target.checked)"
  />
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'FormControlCheckbox',
  props: {
    value: String,
    label: String,
    checked: Boolean,
    disabled: Boolean,
  },
  emits: ['update:checked'],
}
</script>
