// packages/ube/angular/form-control-radio-group.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef } from '@angular/core'

interface RadioOption {
  value: string | number
  label: string
}

/**
 * RadioGroup: fieldset + legend + FormControlRadio options.
 * Angular component for grouping regular radio buttons with aria-disabled support.
 */
@Component({
  selector: 'ube-form-control-radio-group',
  template: `
    <fieldset
      #wrapper
      [attr.aria-disabled]="disabled ? 'true' : undefined"
    >
      <legend class="sr-only">{{ legend }}</legend>
      <div class="radio-group">
        <label *ngFor="let opt of options" class="radio-control">
          <input
            type="radio"
            [name]="name"
            [value]="opt.value"
            [checked]="value === opt.value"
            [disabled]="disabled"
            (change)="handleChange(opt.value)"
          />
          <span>{{ opt.label }}</span>
        </label>
      </div>
    </fieldset>
  `,
  styleUrls: ['../../form-control-radio.css'],
})
export class FormControlRadioGroupComponent {
  @ViewChild('wrapper') wrapper!: ElementRef<HTMLFieldSetElement>

  @Input() legend: string = ''
  @Input() name: string = ''
  @Input() value: string | number | null = null
  @Input() options: RadioOption[] = []
  @Input() disabled = false

  @Output() valueChange = new EventEmitter<string | number>()

  handleChange(newValue: string | number) {
    if (!this.disabled) {
      this.valueChange.emit(newValue)
    }
  }
}

// packages/ube/react/FormControlRadioGroup.jsx
import '../form-control-radio.css'

/**
 * FormControlRadioGroup: fieldset + legend + native radio buttons.
 * Standard radio button group with support for disabled state and custom options.
 *
 * @param {string} legend - Label for the fieldset (required, screen-reader only)
 * @param {string} name - Name attribute for radio inputs (required)
 * @param {string|number} value - Selected value
 * @param {Array} options - Array of { value, label } objects
 * @param {Function} onChange - Called with new value when selection changes
 * @param {boolean} disabled - Disable all radios in group
 * @param {string} className - Additional wrapper classes
 */
function FormControlRadioGroup({
  legend,
  name,
  value,
  options = [],
  onChange,
  disabled = false,
  className = '',
  ...rest
}) {
  const handleChange = (e) => {
    if (!disabled) {
      onChange?.(e.target.value)
    }
  }

  return (
    <fieldset
      className={`radio-group-wrapper${className ? ` ${className}` : ''}`}
      aria-disabled={disabled ? 'true' : undefined}
      {...rest}
    >
      <legend className="sr-only">{legend}</legend>
      <div className="radio-group">
        {options.map((opt) => (
          <label key={opt.value} className="radio-control">
            <input
              type="radio"
              name={name}
              value={opt.value}
              checked={value === opt.value}
              disabled={disabled}
              onChange={handleChange}
            />
            <span>{opt.label}</span>
          </label>
        ))}
      </div>
    </fieldset>
  )
}

export default FormControlRadioGroup
