// packages/ube/vue/Panel.vue
<template>
  <div :class="panelClassName" v-bind="$attrs">
    <div :class="headerClassName">
      <ButtonBack :label="closeAriaLabel" :dir="dir" @click="$emit('close')" />
      <h2 ref="headingRef" tabindex="-1" :class="titleClassName">{{ heading }}</h2>
    </div>
    <slot></slot>
  </div>
</template>

<script>
import { ref } from 'vue'
import ButtonBack from './ButtonBack.vue'
import '../panel.css'

export default {
  name: 'Panel',
  components: { ButtonBack },
  props: {
    heading: { type: String, required: true },
    panelClassName: { type: String, default: '' },
    headerClassName: { type: String, default: '' },
    titleClassName: { type: String, default: '' },
    closeAriaLabel: { type: String, default: 'Close' },
    dir: { type: String, default: 'ltr', validator: (v) => ['ltr', 'rtl'].includes(v) },
  },
  emits: ['close'],
  setup(_, { expose }) {
    const headingRef = ref(null)
    const focus = () => headingRef.value?.focus()
    expose({ focus })
    return { headingRef }
  },
}
</script>

// packages/ube/react/Panel.jsx
import { forwardRef } from 'react'
import ButtonBack from './ButtonBack.jsx'
import '../panel.css'

const Panel = forwardRef(function Panel({
  panelClassName,
  headerClassName,
  titleClassName,
  heading,
  headingRef,
  onClose,
  closeAriaLabel,
  children,
  dir = 'ltr',
  ...rest
}, ref) {
  return (
    <div ref={ref} className={panelClassName} {...rest}>
      <div className={headerClassName}>
        <ButtonBack onClick={onClose} label={closeAriaLabel} dir={dir} />
        <h2 ref={headingRef} tabIndex={-1} className={titleClassName}>
          {heading}
        </h2>
      </div>
      {children}
    </div>
  )
})

export default Panel
