// packages/ube/vue/ButtonText.vue
<template>
  <ube-button-text
    ref="el"
    :variant="variant"
    :disabled="disabled"
    :active="active"
    :full-width="fullWidth"
    :label="label"
    :active-label="activeLabel"
    :title="title"
    @click="$emit('click', $event)"
  />
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'ButtonText',
  props: {
    variant: String,
    disabled: Boolean,
    active: Boolean,
    fullWidth: Boolean,
    label: String,
    activeLabel: String,
    title: String,
    icon: Object,
    activeIcon: Object,
  },
  emits: ['click'],
  methods: {
    focus() {
      this.$refs.el?.focus()
    },
  },
  watch: {
    icon(val) {
      this.$refs.el.icon = val
    },
    activeIcon(val) {
      this.$refs.el.activeIcon = val
    },
  },
  mounted() {
    if (this.icon) {
      this.$refs.el.icon = this.icon
    }
    if (this.activeIcon) {
      this.$refs.el.activeIcon = this.activeIcon
    }
  },
}
</script>

// packages/ube/ng/button-text.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, AfterViewInit, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'
import '@ulam/ube/core'

@Component({
  selector: 'ube-button-text',
  template: `<ube-button-text
    #el
    [attr.variant]="variant"
    [attr.disabled]="disabled"
    [attr.active]="active"
    [attr.full-width]="fullWidth"
    [attr.label]="label"
    [attr.active-label]="activeLabel"
    [attr.title]="title"
    (click)="click.emit($event)"
  ></ube-button-text>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ButtonTextComponent implements AfterViewInit {
  @ViewChild('el') el!: ElementRef<any>
  @Input() variant?: string
  @Input() disabled = false
  @Input() active = false
  @Input() fullWidth = false
  @Input() label?: string
  @Input() activeLabel?: string
  @Input() title?: string
  @Input() set icon(val: any) {
    if (this.el) {
      this.el.nativeElement.icon = val
    }
  }
  @Input() set activeIcon(val: any) {
    if (this.el) {
      this.el.nativeElement.activeIcon = val
    }
  }
  @Output() click = new EventEmitter<any>()

  ngAfterViewInit() {
    // Icon properties set in setters
  }

  focus() {
    this.el?.nativeElement?.focus()
  }
}
