// packages/ube/vue/FadeTransition.vue
<template>
  <ube-fade-transition
    ref="el"
    :watch-key="String(watchKey)"
    :direction="direction"
  >
    <slot />
  </ube-fade-transition>
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'FadeTransition',
  props: {
    watchKey: [String, Number],
    direction: String,
  },
}
</script>

// packages/ube/ng/fade-transition.component.ts
import { Component, Input, ViewChild, ElementRef, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'
import '@ulam/ube/core'

@Component({
  selector: 'ube-fade-transition',
  template: `<ube-fade-transition
    #el
    [attr.watch-key]="String(watchKey)"
    [attr.direction]="direction"
  ><ng-content></ng-content></ube-fade-transition>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class FadeTransitionComponent {
  @ViewChild('el') el!: ElementRef<any>
  @Input() watchKey?: string | number
  @Input() direction?: string
}
