// packages/ube/vue/FormControlSelect.vue
<template>
  <ube-form-control-select
    ref="el"
    :disabled="disabled"
    @change="$emit('update:value', $event.target.value)"
  >
    <slot />
  </ube-form-control-select>
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'FormControlSelect',
  props: {
    disabled: Boolean,
    value: String,
  },
  emits: ['update:value'],
}
</script>

// packages/ube/ng/form-control-select.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'
import '@ulam/ube/core'

@Component({
  selector: 'ube-form-control-select',
  template: `<ube-form-control-select
    #el
    [attr.disabled]="disabled"
    (change)="valueChange.emit($event.target.value)"
  ><ng-content></ng-content></ube-form-control-select>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class FormControlSelectComponent {
  @ViewChild('el') el!: ElementRef<any>
  @Input() disabled = false
  @Input() value?: string
  @Output() valueChange = new EventEmitter<string>()
}
