// packages/ube/vue/FormControlToggle.vue
<template>
  <ube-form-control-toggle
    ref="el"
    :checked="checked"
    :disabled="disabled"
    :label="label"
    @change="$emit('update:checked', $event.target.checked)"
  />
</template>

<script>
import '@ulam/ube/core'

export default {
  name: 'FormControlToggle',
  props: {
    checked: Boolean,
    disabled: Boolean,
    label: String,
  },
  emits: ['update:checked'],
}
</script>

// packages/ube/ng/form-control-toggle.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core'
import '@ulam/ube/core'

@Component({
  selector: 'ube-form-control-toggle',
  template: `<ube-form-control-toggle
    #el
    [attr.checked]="checked"
    [attr.disabled]="disabled"
    [attr.label]="label"
    (change)="checkedChange.emit($event.target.checked)"
  ></ube-form-control-toggle>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class FormControlToggleComponent {
  @ViewChild('el') el!: ElementRef<any>
  @Input() checked = false
  @Input() disabled = false
  @Input() label?: string
  @Output() checkedChange = new EventEmitter<boolean>()
}
